import { terrainAt } from "@border-empires/shared";
import { strategicRibbonHtml } from "./client-panel-html.js";
import { activeTrucesHtml, allianceRequestsHtml, alliesHtml, feedHtml, leaderboardHtml, missionCardsHtml, truceRequestsHtml } from "./client-panel-html.js";
import { busyDevelopmentProcessCount } from "./client-development-queue.js";
import { populationPerMinuteLabel, townNextGrowthEtaLabel } from "./client-town-growth.js";
import { initTerrainTextures } from "./client-map-render.js";
import { computeDragPreview as computeDragPreviewFromModule, worldTileRawFromPointer as worldTileRawFromPointerFromModule } from "./client-drag-selection.js";
import { createClientAppEnv } from "./client-app-env.js";
import { createClientAppFlowDeps } from "./client-app-flow-deps.js";
import { createClientAppRenderDeps } from "./client-app-render-deps.js";

export const createClientAppBootstrapDeps = () => {
  const env = createClientAppEnv();
  const renderDeps = createClientAppRenderDeps(env);
  const flowDeps = createClientAppFlowDeps(env, { ...renderDeps, populationPerMinuteLabel });

  return {
    state: env.state,
    dom: env.dom,
    miniMapReplayEl: env.miniMapReplayEl,
    ws: env.ws,
    wsUrl: env.wsUrl,
    firebaseAuth: env.firebaseAuth,
    googleProvider: env.googleProvider,
    storageSet: env.storageSet,
    visibleCollectSummary: renderDeps.visibleCollectSummary,
    isMobile: renderDeps.isMobile,
    rateToneClass: env.rateToneClass,
    formatGoldAmount: env.formatGoldAmount,
    formatManpowerAmount: env.formatManpowerAmount,
    strategicRibbonHtml,
    openEconomyPanel: renderDeps.openEconomyPanel,
    setActivePanel: renderDeps.setActivePanel,
    mobileNavLabelHtml: renderDeps.mobileNavLabelHtml,
    keyFor: env.key,
    parseKey: env.parseKey,
    selectedTile: flowDeps.selectedTile,
    passiveTileGuidanceHtml: flowDeps.passiveTileGuidanceHtml,
    techFlow: flowDeps.techFlow,
    domainOwnedHtml: renderDeps.domainOwnedHtml,
    techOwnedHtml: renderDeps.techOwnedHtml,
    techCurrentModsHtml: renderDeps.techCurrentModsHtml,
    bindTechTreeDragScroll: renderDeps.bindTechTreeDragScroll,
    alliesHtml,
    activeTrucesHtml,
    allianceRequestsHtml,
    truceRequestsHtml,
    renderSocialInspectCardHtml: renderDeps.renderSocialInspectCardHtml,
    missionCardsHtml,
    playerNameForOwner: renderDeps.playerNameForOwner,
    wrapX: env.wrapX,
    wrapY: env.wrapY,
    terrainAt,
    pushFeed: renderDeps.pushFeed,
    pushFeedEntry: renderDeps.pushFeedEntry,
    requestViewRefresh: renderDeps.requestViewRefresh,
    prettyToken: env.prettyToken,
    resourceIconForKey: renderDeps.resourceIconForKey,
    resourceLabel: renderDeps.resourceLabel,
    economicStructureName: renderDeps.economicStructureName,
    leaderboardHtml,
    feedHtml,
    renderMobilePanels: renderDeps.renderMobilePanels,
    renderManpowerPanelHtml: renderDeps.renderManpowerPanelHtml,
    viewportSize: renderDeps.viewportSize,
    drawMiniMap: renderDeps.drawMiniMap,
    maybeRefreshForCamera: renderDeps.maybeRefreshForCamera,
    shouldPreserveOptimisticExpandByKey: flowDeps.shouldPreserveOptimisticExpandByKey,
    drawTerrainTile: renderDeps.drawTerrainTile,
    drawForestOverlay: renderDeps.drawForestOverlay,
    effectiveOverlayColor: renderDeps.effectiveOverlayColor,
    overlayVariantIndexAt: renderDeps.overlayVariantIndexAt,
    dockOverlayVariants: renderDeps.dockOverlayVariants,
    drawCenteredOverlay: renderDeps.drawCenteredOverlay,
    builtResourceOverlayForTile: renderDeps.builtResourceOverlayForTile,
    resourceOverlayForTile: renderDeps.resourceOverlayForTile,
    economicStructureOverlayAlpha: renderDeps.economicStructureOverlayAlpha,
    drawCenteredOverlayWithAlpha: renderDeps.drawCenteredOverlayWithAlpha,
    resourceOverlayScaleForTile: renderDeps.resourceOverlayScaleForTile,
    drawResourceCornerMarker: renderDeps.drawResourceCornerMarker,
    drawRoadOverlay: renderDeps.drawRoadOverlay,
    fortificationOverlayImageFor: renderDeps.fortificationOverlayImageFor,
    resourceColor: renderDeps.resourceColor,
    shardOverlayForTile: renderDeps.shardOverlayForTile,
    drawShardFallback: renderDeps.drawShardFallback,
    drawTownOverlay: renderDeps.drawTownOverlay,
    hasCollectableYield: renderDeps.hasCollectableYield,
    structureAccentColor: renderDeps.structureAccentColor,
    structureOverlayImages: renderDeps.structureOverlayImages,
    shouldDrawOwnershipBorder: renderDeps.shouldDrawOwnershipBorder,
    borderColorForOwner: renderDeps.borderColorForOwner,
    borderLineWidthForOwner: renderDeps.borderLineWidthForOwner,
    drawExposedTileBorder: renderDeps.drawExposedTileBorder,
    originSelection: flowDeps.originSelection,
    worldToScreen: renderDeps.worldToScreen,
    isDockRouteVisibleForPlayer: renderDeps.isDockRouteVisibleForPlayer,
    computeDockSeaRoute: renderDeps.computeDockSeaRoute,
    toroidDelta: renderDeps.toroidDelta,
    drawAetherBridgeLane: renderDeps.drawAetherBridgeLane,
    clearOptimisticTileState: flowDeps.clearOptimisticTileState,
    mergeIncomingTileDetail: flowDeps.mergeIncomingTileDetail,
    mergeServerTileWithOptimisticState: flowDeps.mergeServerTileWithOptimisticState,
    maybeAnnounceShardSite: renderDeps.maybeAnnounceShardSite,
    markDockDiscovered: renderDeps.markDockDiscovered,
    centerOnOwnedTile: renderDeps.centerOnOwnedTile,
    defensibilityPctFromTE: flowDeps.defensibilityPctFromTE,
    clearPendingCollectVisibleDelta: renderDeps.clearPendingCollectVisibleDelta,
    resetStrategicReplayState: renderDeps.resetStrategicReplayState,
    setWorldSeed: env.setWorldSeed,
    clearRenderCaches: renderDeps.clearRenderCaches,
    buildMiniMapBase: renderDeps.buildMiniMapBase,
    shardAlertKeyForPayload: renderDeps.shardAlertKeyForPayload,
    showShardAlert: renderDeps.showShardAlert,
    combatResolutionAlert: flowDeps.combatResolutionAlert,
    wasPredictedCombatAlreadyShown: flowDeps.wasPredictedCombatAlreadyShown,
    showCaptureAlert: renderDeps.showCaptureAlert,
    notifyInsufficientGoldForFrontierAction: renderDeps.notifyInsufficientGoldForFrontierAction,
    clearPendingCollectTileDelta: renderDeps.clearPendingCollectTileDelta,
    revertOptimisticVisibleCollectDelta: renderDeps.revertOptimisticVisibleCollectDelta,
    revertOptimisticTileCollectDelta: renderDeps.revertOptimisticTileCollectDelta,
    applyOptimisticVisibleCollect: renderDeps.applyOptimisticVisibleCollect,
    applyOptimisticTileCollect: renderDeps.applyOptimisticTileCollect,
    applyOptimisticTileState: flowDeps.applyOptimisticTileState,
    applyOptimisticStructureBuild: flowDeps.applyOptimisticStructureBuild,
    applyOptimisticStructureRemoval: flowDeps.applyOptimisticStructureRemoval,
    applyOptimisticStructureCancel: flowDeps.applyOptimisticStructureCancel,
    ownerSpawnShieldActive: renderDeps.ownerSpawnShieldActive,
    supportedOwnedTownsForTile: flowDeps.supportedOwnedTownsForTile,
    supportedOwnedDocksForTile: flowDeps.supportedOwnedDocksForTile,
    townHasSupportStructure: flowDeps.townHasSupportStructure,
    growthModifierPercentLabel: flowDeps.growthModifierPercentLabel,
    structureGoldCost: env.structureGoldCost,
    structureCostText: env.structureCostText,
    busyDevelopmentProcessCount,
    populationPerMinuteLabel,
    townNextGrowthEtaLabel,
    tileVisibilityStateAt: renderDeps.tileVisibilityStateAt,
    techPickEl: env.dom.techPickEl,
    mobileTechPickEl: env.dom.mobileTechPickEl,
    canvas: env.dom.canvas,
    holdBuildMenuEl: env.dom.holdBuildMenuEl,
    tileActionMenuEl: env.dom.tileActionMenuEl,
    authColorPresetButtons: env.dom.authColorPresetButtons,
    authProfileColorEl: env.dom.authProfileColorEl,
    authEmailEl: env.dom.authEmailEl,
    authEmailLinkBtn: env.dom.authEmailLinkBtn,
    authProfileNameEl: env.dom.authProfileNameEl,
    authProfileSaveBtn: env.dom.authProfileSaveBtn,
    allianceSendBtn: env.dom.allianceSendBtn,
    mobileAllianceSendBtn: env.dom.mobileAllianceSendBtn,
    allianceBreakBtn: env.dom.allianceBreakBtn,
    mobileAllianceBreakBtn: env.dom.mobileAllianceBreakBtn,
    allianceTargetEl: env.dom.allianceTargetEl,
    mobileAllianceTargetEl: env.dom.mobileAllianceTargetEl,
    allianceBreakIdEl: env.dom.allianceBreakIdEl,
    mobileAllianceBreakIdEl: env.dom.mobileAllianceBreakIdEl,
    techChooseBtn: env.dom.techChooseBtn,
    mobileTechChooseBtn: env.dom.mobileTechChooseBtn,
    centerMeBtn: env.dom.centerMeBtn,
    centerMeDesktopBtn: env.dom.centerMeDesktopBtn,
    collectVisibleDesktopBtn: env.dom.collectVisibleDesktopBtn,
    collectVisibleMobileBtn: env.dom.collectVisibleMobileBtn,
    captureCancelBtn: env.dom.captureCancelBtn,
    captureCloseBtn: env.dom.captureCloseBtn,
    captureTimeEl: env.dom.captureTimeEl,
    shardAlertCloseBtn: env.dom.shardAlertCloseBtn,
    panelCloseBtn: env.dom.panelCloseBtn,
    panelActionButtons: env.dom.panelActionButtons,
    miniMapEl: env.dom.miniMapEl,
    ctx: env.dom.ctx,
    initTerrainTextures,
    worldTileRawFromPointerFromModule,
    computeDragPreviewFromModule,
    terrainLabel: env.terrainLabel,
    displayTownGoldPerMinute: flowDeps.displayTownGoldPerMinute,
    tileHistoryLines: flowDeps.tileHistoryLines,
    hideShardAlert: renderDeps.hideShardAlert,
    showCollectVisibleCooldownAlert: renderDeps.showCollectVisibleCooldownAlert,
    drawBarbarianSkullOverlay: renderDeps.drawBarbarianSkullOverlay,
    drawIncomingAttackOverlay: renderDeps.drawIncomingAttackOverlay,
    COLLECT_VISIBLE_COOLDOWN_MS: renderDeps.COLLECT_VISIBLE_COOLDOWN_MS
  };
};
