import { bindClientMapInput } from "./client-map-input.js";
import { bindClientNetwork } from "./client-network.js";
import { resizeClientViewport } from "./client-hud.js";
import { bindClientUiControls } from "./client-ui-controls.js";
import { startClientRuntimeLoop } from "./client-runtime-loop.js";

type BootstrapBindingsContext = Record<string, any>;

export const bindClientBootstrap = (ctx: BootstrapBindingsContext): void => {
  const resize = (): void => resizeClientViewport({ dom: { canvas: ctx.canvas }, viewportSize: ctx.viewportSize });
  window.addEventListener("resize", resize);
  window.visualViewport?.addEventListener("resize", resize);
  resize();
  ctx.authFlow.bindAuthUi();

  bindClientUiControls({
    state: ctx.state,
    hud: ctx.dom.hud,
    allianceSendBtn: ctx.allianceSendBtn,
    mobileAllianceSendBtn: ctx.mobileAllianceSendBtn,
    allianceBreakBtn: ctx.allianceBreakBtn,
    mobileAllianceBreakBtn: ctx.mobileAllianceBreakBtn,
    allianceTargetEl: ctx.allianceTargetEl,
    mobileAllianceTargetEl: ctx.mobileAllianceTargetEl,
    allianceBreakIdEl: ctx.allianceBreakIdEl,
    mobileAllianceBreakIdEl: ctx.mobileAllianceBreakIdEl,
    techChooseBtn: ctx.techChooseBtn,
    mobileTechChooseBtn: ctx.mobileTechChooseBtn,
    techPickEl: ctx.techPickEl,
    mobileTechPickEl: ctx.mobileTechPickEl,
    centerMeBtn: ctx.centerMeBtn,
    centerMeDesktopBtn: ctx.centerMeDesktopBtn,
    collectVisibleDesktopBtn: ctx.collectVisibleDesktopBtn,
    collectVisibleMobileBtn: ctx.collectVisibleMobileBtn,
    captureCancelBtn: ctx.captureCancelBtn,
    captureCloseBtn: ctx.captureCloseBtn,
    captureTimeEl: ctx.captureTimeEl,
    shardAlertCloseBtn: ctx.shardAlertCloseBtn,
    panelCloseBtn: ctx.panelCloseBtn,
    panelActionButtons: ctx.panelActionButtons,
    authColorPresetButtons: ctx.authColorPresetButtons,
    authProfileColorEl: ctx.authProfileColorEl,
    authEmailEl: ctx.authEmailEl,
    authEmailLinkBtn: ctx.authEmailLinkBtn,
    authProfileNameEl: ctx.authProfileNameEl,
    authProfileSaveBtn: ctx.authProfileSaveBtn,
    sendAllianceRequest: ctx.actionFlow.sendAllianceRequest,
    breakAlliance: ctx.actionFlow.breakAlliance,
    chooseTech: ctx.actionFlow.chooseTech,
    renderHud: ctx.renderHud,
    centerOnOwnedTile: ctx.centerOnOwnedTile,
    requestViewRefresh: ctx.requestViewRefresh,
    collectVisibleYield: ctx.actionFlow.collectVisibleYield,
    cancelOngoingCapture: ctx.actionFlow.cancelOngoingCapture,
    hideShardAlert: ctx.hideShardAlert,
    renderShardAlert: ctx.renderShardAlert,
    renderCaptureProgress: ctx.renderCaptureProgress,
    setActivePanel: ctx.setActivePanel,
    syncAuthPanelState: ctx.syncAuthPanelState
  });

  bindClientNetwork({
    state: ctx.state,
    ws: ctx.ws,
    wsUrl: ctx.wsUrl,
    firebaseAuth: ctx.firebaseAuth,
    keyFor: ctx.keyFor,
    renderHud: ctx.renderHud,
    setAuthStatus: ctx.setAuthStatus,
    syncAuthOverlay: ctx.syncAuthOverlay,
    authenticateSocket: ctx.authenticateSocket,
    pushFeed: ctx.pushFeed,
    pushFeedEntry: ctx.pushFeedEntry,
    clearOptimisticTileState: ctx.clearOptimisticTileState,
    requestViewRefresh: ctx.requestViewRefresh,
    applyPendingSettlementsFromServer: ctx.actionFlow.applyPendingSettlementsFromServer,
    mergeIncomingTileDetail: ctx.mergeIncomingTileDetail,
    mergeServerTileWithOptimisticState: ctx.mergeServerTileWithOptimisticState,
    maybeAnnounceShardSite: ctx.maybeAnnounceShardSite,
    markDockDiscovered: ctx.markDockDiscovered,
    centerOnOwnedTile: ctx.centerOnOwnedTile,
    authProfileNameEl: ctx.authProfileNameEl,
    authProfileColorEl: ctx.authProfileColorEl,
    defensibilityPctFromTE: ctx.techFlow.defensibilityPctFromTE,
    clearPendingCollectVisibleDelta: ctx.clearPendingCollectVisibleDelta,
    seedProfileSetupFields: ctx.seedProfileSetupFields,
    resetStrategicReplayState: ctx.resetStrategicReplayState,
    setWorldSeed: ctx.setWorldSeed,
    clearRenderCaches: ctx.clearRenderCaches,
    buildMiniMapBase: ctx.buildMiniMapBase,
    shardAlertKeyForPayload: ctx.shardAlertKeyForPayload,
    showShardAlert: ctx.showShardAlert,
    combatResolutionAlert: ctx.combatResolutionAlert,
    wasPredictedCombatAlreadyShown: ctx.wasPredictedCombatAlreadyShown,
    showCaptureAlert: ctx.showCaptureAlert,
    requestSettlement: ctx.actionFlow.requestSettlement,
    dropQueuedTargetKeyIfAbsent: ctx.actionFlow.dropQueuedTargetKeyIfAbsent,
    processActionQueue: ctx.actionFlow.processActionQueue,
    clearSettlementProgressForTile: ctx.actionFlow.clearSettlementProgressForTile,
    terrainAt: ctx.terrainAt,
    requestAttackPreviewForTarget: ctx.actionFlow.requestAttackPreviewForTarget,
    openSingleTileActionMenu: ctx.actionFlow.openSingleTileActionMenu,
    isTileOwnedByAlly: ctx.actionFlow.isTileOwnedByAlly,
    hideShardAlert: ctx.hideShardAlert,
    explainActionFailure: ctx.actionFlow.explainActionFailure,
    notifyInsufficientGoldForFrontierAction: ctx.notifyInsufficientGoldForFrontierAction,
    clearSettlementProgressByKey: ctx.actionFlow.clearSettlementProgressByKey,
    showCollectVisibleCooldownAlert: ctx.showCollectVisibleCooldownAlert,
    formatCooldownShort: ctx.actionFlow.formatCooldownShort,
    reconcileActionQueue: ctx.actionFlow.reconcileActionQueue,
    revertOptimisticVisibleCollectDelta: ctx.revertOptimisticVisibleCollectDelta,
    revertOptimisticTileCollectDelta: ctx.revertOptimisticTileCollectDelta,
    clearPendingCollectTileDelta: ctx.clearPendingCollectTileDelta,
    playerNameForOwner: ctx.playerNameForOwner,
    settlementProgressForTile: ctx.actionFlow.settlementProgressForTile,
    COLLECT_VISIBLE_COOLDOWN_MS: ctx.COLLECT_VISIBLE_COOLDOWN_MS,
    shouldResetFrontierActionStateForError: ctx.actionFlow.shouldResetFrontierActionStateForError
  });

  ctx.authFlow.bindFirebaseAuth();

  startClientRuntimeLoop(ctx.state, {
    canvas: ctx.canvas,
    ctx: ctx.ctx,
    initTerrainTextures: ctx.initTerrainTextures,
    isMobile: ctx.isMobile,
    keyFor: ctx.keyFor,
    wrapX: ctx.wrapX,
    wrapY: ctx.wrapY,
    parseKey: ctx.parseKey,
    selectedTile: ctx.selectedTile,
    settlementProgressForTile: ctx.actionFlow.settlementProgressForTile,
    tileVisibilityStateAt: ctx.tileVisibilityStateAt,
    crystalTargetingTone: ctx.actionFlow.crystalTargetingTone,
    startingExpansionArrowTargets: ctx.originSelection.startingExpansionArrowTargets,
    drawTerrainTile: ctx.drawTerrainTile,
    drawForestOverlay: ctx.drawForestOverlay,
    effectiveOverlayColor: ctx.effectiveOverlayColor,
    overlayVariantIndexAt: ctx.overlayVariantIndexAt,
    dockOverlayVariants: ctx.dockOverlayVariants,
    drawCenteredOverlay: ctx.drawCenteredOverlay,
    builtResourceOverlayForTile: ctx.builtResourceOverlayForTile,
    resourceOverlayForTile: ctx.resourceOverlayForTile,
    economicStructureOverlayAlpha: ctx.economicStructureOverlayAlpha,
    drawCenteredOverlayWithAlpha: ctx.drawCenteredOverlayWithAlpha,
    resourceOverlayScaleForTile: ctx.resourceOverlayScaleForTile,
    drawResourceCornerMarker: ctx.drawResourceCornerMarker,
    drawRoadOverlay: ctx.drawRoadOverlay,
    fortificationOverlayImageFor: ctx.fortificationOverlayImageFor,
    resourceColor: ctx.resourceColor,
    shardOverlayForTile: ctx.shardOverlayForTile,
    drawShardFallback: ctx.drawShardFallback,
    drawTownOverlay: ctx.drawTownOverlay,
    hasCollectableYield: ctx.hasCollectableYield,
    structureAccentColor: ctx.structureAccentColor,
    structureOverlayImages: ctx.structureOverlayImages,
    constructionRemainingMsForTile: ctx.actionFlow.constructionRemainingMsForTile,
    formatCountdownClock: ctx.actionFlow.formatCountdownClock,
    drawStartingExpansionArrow: ctx.drawStartingExpansionArrow,
    drawBarbarianSkullOverlay: ctx.drawBarbarianSkullOverlay,
    shouldDrawOwnershipBorder: ctx.shouldDrawOwnershipBorder,
    borderColorForOwner: ctx.borderColorForOwner,
    isTileOwnedByAlly: ctx.actionFlow.isTileOwnedByAlly,
    borderLineWidthForOwner: ctx.borderLineWidthForOwner,
    drawExposedTileBorder: ctx.drawExposedTileBorder,
    isTownSupportNeighbor: ctx.originSelection.isTownSupportNeighbor,
    isTownSupportHighlightableTile: ctx.originSelection.isTownSupportHighlightableTile,
    drawIncomingAttackOverlay: ctx.drawIncomingAttackOverlay,
    settlePixelWanderPoint: ctx.settlePixelWanderPoint,
    worldToScreen: ctx.worldToScreen,
    isDockRouteVisibleForPlayer: ctx.isDockRouteVisibleForPlayer,
    computeDockSeaRoute: ctx.computeDockSeaRoute,
    toroidDelta: ctx.toroidDelta,
    drawAetherBridgeLane: ctx.drawAetherBridgeLane,
    drawMiniMap: ctx.drawMiniMap,
    maybeRefreshForCamera: ctx.maybeRefreshForCamera,
    renderHud: ctx.renderHud,
    renderCaptureProgress: ctx.renderCaptureProgress,
    renderShardAlert: ctx.renderShardAlert,
    cleanupExpiredSettlementProgress: ctx.actionFlow.cleanupExpiredSettlementProgress,
    processDevelopmentQueue: ctx.actionFlow.processDevelopmentQueue,
    clearOptimisticTileState: ctx.clearOptimisticTileState,
    dropQueuedTargetKeyIfAbsent: ctx.actionFlow.dropQueuedTargetKeyIfAbsent,
    pushFeed: ctx.pushFeed,
    processActionQueue: ctx.actionFlow.processActionQueue,
    shouldPreserveOptimisticExpandByKey: ctx.shouldPreserveOptimisticExpandByKey,
    requestViewRefresh: ctx.requestViewRefresh,
    reconcileActionQueue: ctx.actionFlow.reconcileActionQueue
  });

  bindClientMapInput(ctx.state, {
    canvas: ctx.canvas,
    miniMapEl: ctx.miniMapEl,
    holdBuildMenuEl: ctx.holdBuildMenuEl,
    tileActionMenuEl: ctx.tileActionMenuEl,
    wrapX: ctx.wrapX,
    wrapY: ctx.wrapY,
    keyFor: ctx.keyFor,
    worldTileRawFromPointer: ctx.worldTileRawFromPointer,
    computeDragPreview: ctx.computeDragPreview,
    requestViewRefresh: ctx.requestViewRefresh,
    maybeRefreshForCamera: ctx.maybeRefreshForCamera,
    handleTileSelection: ctx.actionFlow.handleTileSelection,
    cancelOngoingCapture: ctx.actionFlow.cancelOngoingCapture,
    hideHoldBuildMenu: ctx.actionFlow.hideHoldBuildMenu,
    hideTileActionMenu: ctx.actionFlow.hideTileActionMenu,
    clearCrystalTargeting: ctx.actionFlow.clearCrystalTargeting,
    renderMobilePanels: ctx.renderMobilePanels,
    queueSpecificTargets: ctx.actionFlow.queueSpecificTargets,
    processActionQueue: ctx.actionFlow.processActionQueue,
    pushFeed: ctx.pushFeed,
    openBulkTileActionMenu: ctx.actionFlow.openBulkTileActionMenu,
    isTileOwnedByAlly: ctx.actionFlow.isTileOwnedByAlly,
    requestAttackPreviewForHover: ctx.actionFlow.requestAttackPreviewForHover,
    interactionFlags: ctx.actionFlow.mapInteractionFlags
  });

  ctx.renderHud();
};
