import { createClientAuthFlow } from "./client-auth-flow.js";
import { createClientActionFlow } from "./client-action-flow.js";
import {
  drawStartingExpansionArrow as drawStartingExpansionArrowFromModule,
  renderCaptureProgress as renderCaptureProgressFromModule,
  renderShardAlert as renderShardAlertFromModule,
  settlePixelWanderPoint as settlePixelWanderPointFromModule
} from "./client-capture-effects.js";
import { bindClientMapInput } from "./client-map-input.js";
import { bindClientNetwork } from "./client-network.js";
import { renderClientHud, resizeClientViewport } from "./client-hud.js";
import { bindClientUiControls } from "./client-ui-controls.js";
import { startClientRuntimeLoop } from "./client-runtime-loop.js";

type BootstrapDeps = Record<string, any>;

export const bootstrapClientApp = (deps: BootstrapDeps): void => {
  const {
    state,
    dom,
    miniMapReplayEl,
    ws,
    wsUrl,
    firebaseAuth,
    googleProvider,
    storageSet,
    visibleCollectSummary,
    isMobile,
    rateToneClass,
    formatGoldAmount,
    formatManpowerAmount,
    strategicRibbonHtml,
    openEconomyPanel,
    setActivePanel,
    mobileNavLabelHtml,
    keyFor,
    parseKey,
    selectedTile,
    passiveTileGuidanceHtml,
    techFlow,
    domainOwnedHtml,
    techOwnedHtml,
    techCurrentModsHtml,
    bindTechTreeDragScroll,
    alliesHtml,
    activeTrucesHtml,
    allianceRequestsHtml,
    truceRequestsHtml,
    renderSocialInspectCardHtml,
    missionCardsHtml,
    playerNameForOwner,
    wrapX,
    wrapY,
    terrainAt,
    pushFeed,
    pushFeedEntry,
    requestViewRefresh,
    prettyToken,
    resourceIconForKey,
    resourceLabel,
    economicStructureName,
    leaderboardHtml,
    feedHtml,
    renderMobilePanels,
    renderManpowerPanelHtml,
    viewportSize,
    drawMiniMap,
    maybeRefreshForCamera,
    shouldPreserveOptimisticExpandByKey,
    drawTerrainTile,
    drawForestOverlay,
    effectiveOverlayColor,
    overlayVariantIndexAt,
    dockOverlayVariants,
    drawCenteredOverlay,
    builtResourceOverlayForTile,
    resourceOverlayForTile,
    economicStructureOverlayAlpha,
    drawCenteredOverlayWithAlpha,
    resourceOverlayScaleForTile,
    drawResourceCornerMarker,
    drawRoadOverlay,
    resourceColor,
    shardOverlayForTile,
    drawShardFallback,
    drawTownOverlay,
    hasCollectableYield,
    structureAccentColor,
    structureOverlayImages,
    shouldDrawOwnershipBorder,
    borderColorForOwner,
    borderLineWidthForOwner,
    drawExposedTileBorder,
    originSelection,
    worldToScreen,
    isDockRouteVisibleForPlayer,
    computeDockSeaRoute,
    toroidDelta,
    drawAetherBridgeLane,
    clearOptimisticTileState,
    mergeIncomingTileDetail,
    mergeServerTileWithOptimisticState,
    maybeAnnounceShardSite,
    markDockDiscovered,
    centerOnOwnedTile,
    defensibilityPctFromTE,
    clearPendingCollectVisibleDelta,
    seedProfileSetupFields: seedProfileSetupFieldsFromMain,
    resetStrategicReplayState,
    setWorldSeed,
    clearRenderCaches,
    buildMiniMapBase,
    shardAlertKeyForPayload,
    showShardAlert,
    combatResolutionAlert,
    wasPredictedCombatAlreadyShown,
    showCaptureAlert,
    notifyInsufficientGoldForFrontierAction,
    clearPendingCollectTileDelta,
    revertOptimisticVisibleCollectDelta,
    revertOptimisticTileCollectDelta,
    applyOptimisticVisibleCollect,
    applyOptimisticTileCollect,
    applyOptimisticTileState,
    applyOptimisticStructureBuild,
    applyOptimisticStructureCancel,
    ownerSpawnShieldActive,
    supportedOwnedTownsForTile,
    supportedOwnedDocksForTile,
    townHasSupportStructure,
    growthModifierPercentLabel,
    structureGoldCost,
    structureCostText,
    busyDevelopmentProcessCount,
    populationPerMinuteLabel,
    townNextGrowthEtaLabel,
    tileVisibilityStateAt,
    techPickEl,
    mobileTechPickEl,
    canvas,
    holdBuildMenuEl,
    tileActionMenuEl,
    authColorPresetButtons,
    authProfileColorEl,
    authEmailEl,
    authEmailLinkBtn,
    authProfileNameEl,
    authProfileSaveBtn,
    allianceSendBtn,
    mobileAllianceSendBtn,
    allianceBreakBtn,
    mobileAllianceBreakBtn,
    allianceTargetEl,
    mobileAllianceTargetEl,
    allianceBreakIdEl,
    mobileAllianceBreakIdEl,
    techChooseBtn,
    mobileTechChooseBtn,
    centerMeBtn,
    centerMeDesktopBtn,
    collectVisibleDesktopBtn,
    collectVisibleMobileBtn,
    captureCancelBtn,
    captureCloseBtn,
    captureTimeEl,
    shardAlertCloseBtn,
    panelCloseBtn,
    panelActionButtons,
    miniMapEl,
    ctx,
    initTerrainTextures
  } = deps;

  let renderHudImpl = (): void => {};
  let requireAuthedSessionImpl = (_message?: string): boolean => false;

  const authFlow = createClientAuthFlow({
    state,
    dom,
    firebaseAuth,
    googleProvider,
    ws,
    wsUrl,
    requireAuthedSession: (message?: string) => requireAuthedSessionImpl(message),
    renderHud: () => renderHudImpl()
  });

  const { setAuthStatus, syncAuthPanelState, syncAuthOverlay, seedProfileSetupFields, authenticateSocket } = authFlow;

  const requireAuthedSession = (message = "Finish sign-in before interacting with the map."): boolean => {
    if (ws.readyState !== ws.OPEN) {
      setAuthStatus(`Game server unavailable at ${wsUrl}.`, "error");
      syncAuthOverlay();
      return false;
    }
    if (state.authSessionReady) return true;
    setAuthStatus(message, "error");
    syncAuthOverlay();
    return false;
  };
  requireAuthedSessionImpl = requireAuthedSession;

  const worldTileRawFromPointer = (offsetX: number, offsetY: number): { gx: number; gy: number } =>
    deps.worldTileRawFromPointerFromModule(state, canvas, offsetX, offsetY);

  const computeDragPreview = (): void =>
    deps.computeDragPreviewFromModule({ state, canvas, wrapX, wrapY, keyFor, hasCollectableYield });

  const actionFlow = createClientActionFlow({
    state,
    ws,
    wsUrl,
    canvas,
    techPickEl,
    mobileTechPickEl,
    tileActionMenuEl,
    holdBuildMenuEl,
    keyFor,
    parseKey,
    wrapX,
    wrapY,
    terrainAt,
    viewportSize,
    isAdjacent: originSelection.isAdjacent,
    pickOriginForTarget: originSelection.pickOriginForTarget,
    setAuthStatus,
    syncAuthOverlay,
    pushFeed,
    renderHud: () => renderHudImpl(),
    requestViewRefresh,
    selectedTile,
    applyOptimisticTileState,
    clearOptimisticTileState,
    applyOptimisticStructureBuild,
    applyOptimisticStructureCancel,
    mergeServerTileWithOptimisticState,
    playerNameForOwner,
    ownerSpawnShieldActive,
    hasCollectableYield,
    worldTileRawFromPointer,
    computeDragPreview,
    showCaptureAlert,
    showCollectVisibleCooldownAlert: deps.showCollectVisibleCooldownAlert,
    notifyInsufficientGoldForFrontierAction,
    isMobile,
    supportedOwnedTownsForTile,
    supportedOwnedDocksForTile,
    townHasSupportStructure,
    prettyToken,
    terrainLabel: deps.terrainLabel,
    displayTownGoldPerMinute: deps.displayTownGoldPerMinute,
    tileHistoryLines: deps.tileHistoryLines,
    growthModifierPercentLabel,
    structureGoldCost,
    structureCostText,
    busyDevelopmentProcessCount,
    wasPredictedCombatAlreadyShown,
    combatResolutionAlert,
    applyOptimisticVisibleCollect,
    applyOptimisticTileCollect,
    economicStructureName,
    populationPerMinuteLabel,
    townNextGrowthEtaLabel,
    tileVisibilityStateAt
  });

  const renderCaptureProgress = (): void =>
    renderCaptureProgressFromModule(state, {
      keyFor,
      formatCooldownShort: actionFlow.formatCooldownShort,
      showCaptureAlert,
      pushFeed,
      finalizePredictedCombat: (result) => actionFlow.applyCombatOutcomeMessage(result, { predicted: true }),
      captureCardEl: dom.captureCardEl,
      captureWrapEl: dom.captureWrapEl,
      captureCancelBtn: dom.captureCancelBtn,
      captureCloseBtn: dom.captureCloseBtn,
      captureBarEl: dom.captureBarEl,
      captureTitleEl: dom.captureTitleEl,
      captureTimeEl: dom.captureTimeEl,
      captureTargetEl: dom.captureTargetEl
    });

  const renderShardAlert = (): void =>
    renderShardAlertFromModule(state, {
      shardAlertOverlayEl: dom.shardAlertOverlayEl,
      shardAlertTitleEl: dom.shardAlertTitleEl,
      shardAlertDetailEl: dom.shardAlertDetailEl
    });

  const drawStartingExpansionArrow = (px: number, py: number, size: number, dx: number, dy: number): void =>
    drawStartingExpansionArrowFromModule(ctx, px, py, size, dx, dy);

  const renderHud = (): void =>
    renderClientHud({
      state,
      dom: {
        alliancePlayerInspectEl: dom.alliancePlayerInspectEl,
        allianceRequestsEl: dom.allianceRequestsEl,
        alliesListEl: dom.alliesListEl,
        authOverlayEl: dom.authOverlayEl,
        canvas: dom.canvas,
        collectVisibleDesktopBtn: dom.collectVisibleDesktopBtn,
        collectVisibleDesktopMetaEl: dom.collectVisibleDesktopMetaEl,
        collectVisibleMobileBtn: dom.collectVisibleMobileBtn,
        collectVisibleMobileMetaEl: dom.collectVisibleMobileMetaEl,
        feedEl: dom.feedEl,
        guideOverlayEl: dom.guideOverlayEl,
        hoverEl: dom.hoverEl,
        hud: dom.hud,
        leaderboardEl: dom.leaderboardEl,
        mapLoadingMetaEl: dom.mapLoadingMetaEl,
        mapLoadingOverlayEl: dom.mapLoadingOverlayEl,
        mapLoadingTitleEl: dom.mapLoadingTitleEl,
        miniMapLabelEl: dom.miniMapLabelEl,
        missionsEl: dom.missionsEl,
        mobileAlliancePlayerInspectEl: dom.mobileAlliancePlayerInspectEl,
        mobileAllianceRequestsEl: dom.mobileAllianceRequestsEl,
        mobileAlliesListEl: dom.mobileAlliesListEl,
        mobileCoreHelpEl: dom.mobileCoreHelpEl,
        mobilePanelDefensibilityEl: dom.mobilePanelDefensibilityEl,
        mobileFeedEl: dom.mobileFeedEl,
        mobileLeaderboardEl: dom.mobileLeaderboardEl,
        mobilePanelDomainsEl: dom.mobilePanelDomainsEl,
        mobilePanelEconomyEl: dom.mobilePanelEconomyEl,
        mobilePanelManpowerEl: dom.mobilePanelManpowerEl,
        mobilePanelMissionsEl: dom.mobilePanelMissionsEl,
        mobilePanelTechEl: dom.mobilePanelTechEl,
        mobileTechChoiceDetailsEl: dom.mobileTechChoiceDetailsEl,
        mobileTechChoicesGridEl: dom.mobileTechChoicesGridEl,
        mobileTechChooseBtn: dom.mobileTechChooseBtn,
        mobileTechCurrentModsEl: dom.mobileTechCurrentModsEl,
        mobileTechDetailCardEl: dom.mobileTechDetailCardEl,
        mobileTechOwnedEl: dom.mobileTechOwnedEl,
        mobileTechPickEl: dom.mobileTechPickEl,
        mobileTechPointsEl: dom.mobileTechPointsEl,
        mobileTechTreeExpandToggleEl: dom.mobileTechTreeExpandToggleEl,
        panelActionButtons: dom.panelActionButtons,
        panelDefensibilityEl: dom.panelDefensibilityEl,
        panelDomainsEl: dom.panelDomainsEl,
        panelDomainsContentEl: dom.panelDomainsContentEl,
        panelEconomyEl: dom.panelEconomyEl,
        panelManpowerEl: dom.panelManpowerEl,
        panelTechEl: dom.panelTechEl,
        selectedEl: dom.selectedEl,
        statsChipsEl: dom.statsChipsEl,
        structureInfoOverlayEl: dom.structureInfoOverlayEl,
        techDetailOverlayEl: dom.techDetailOverlayEl,
        targetingOverlayEl: dom.targetingOverlayEl,
        techChoiceDetailsEl: dom.techChoiceDetailsEl,
        techChoicesGridEl: dom.techChoicesGridEl,
        techChooseBtn: dom.techChooseBtn,
        techCurrentModsEl: dom.techCurrentModsEl,
        techDetailCardEl: dom.techDetailCardEl,
        techOwnedEl: dom.techOwnedEl,
        techPickEl: dom.techPickEl,
        techPointsEl: dom.techPointsEl,
        techTreeExpandToggleEl: dom.techTreeExpandToggleEl,
        tileActionMenuEl: dom.tileActionMenuEl,
        mapLoadingRowEl: dom.mapLoadingRowEl,
        mapLoadingSpinnerEl: dom.mapLoadingSpinnerEl,
        shardAlertCardEl: dom.shardAlertCardEl,
        shardAlertCloseBtn: dom.shardAlertCloseBtn,
        shardAlertDetailEl: dom.shardAlertDetailEl,
        shardAlertOverlayEl: dom.shardAlertOverlayEl,
        shardAlertTitleEl: dom.shardAlertTitleEl
      },
      miniMapReplayEl,
      wsUrl,
      firebaseAuth,
      syncAuthOverlay,
      storageSet,
      visibleCollectSummary,
      developmentSlotSummary: actionFlow.developmentSlotSummary,
      isMobile,
      rateToneClass,
      formatGoldAmount,
      formatManpowerAmount,
      strategicRibbonHtml,
      formatCooldownShort: actionFlow.formatCooldownShort,
      openEconomyPanel,
      setActivePanel,
      affordableTechChoicesCount: techFlow.affordableTechChoicesCount,
      mobileNavLabelHtml,
      crystalTargetingTone: actionFlow.crystalTargetingTone,
      crystalTargetingTitle: actionFlow.crystalTargetingTitle,
      clearCrystalTargeting: actionFlow.clearCrystalTargeting,
      keyFor,
      parseKey,
      selectedTile,
      requestTileDetailIfNeeded: actionFlow.requestTileDetailIfNeeded,
      passiveTileGuidanceHtml,
      renderTileActionMenu: actionFlow.renderTileActionMenu,
      tileMenuViewForTile: actionFlow.tileMenuViewForTile,
      renderCaptureProgress,
      renderShardAlert,
      renderTechChoiceGrid: techFlow.renderTechChoiceGrid,
      techDetailsUseOverlay: techFlow.techDetailsUseOverlay,
      renderTechDetailPrompt: techFlow.renderTechDetailPrompt,
      renderTechDetailCard: techFlow.renderTechDetailCard,
      renderStructureInfoOverlay: techFlow.renderStructureInfoOverlay,
      renderTechDetailOverlay: techFlow.renderTechDetailOverlay,
      renderDomainDetailOverlay: techFlow.renderDomainDetailOverlay,
      techOwnedHtml,
      effectiveOwnedTechIds: techFlow.effectiveOwnedTechIds,
      isPendingTechUnlock: techFlow.isPendingTechUnlock,
      renderTechChoiceDetails: techFlow.renderTechChoiceDetails,
      techCurrentModsHtml,
      bindTechTreeDragScroll,
      chooseTech: actionFlow.chooseTech,
      renderDomainProgressCard: techFlow.renderDomainProgressCard,
      renderDomainChoiceGrid: techFlow.renderDomainChoiceGrid,
      domainOwnedHtml,
      renderDomainDetailCard: techFlow.renderDomainDetailCard,
      sendGameMessage: actionFlow.sendGameMessage,
      alliesHtml,
      activeTrucesHtml,
      allianceRequestsHtml,
      truceRequestsHtml,
      renderSocialInspectCardHtml,
      missionCardsHtml,
      playerNameForOwner,
      wrapX,
      wrapY,
      terrainAt,
      pushFeed,
      requestViewRefresh,
      prettyToken,
      resourceIconForKey,
      resourceLabel,
      economicStructureName,
      leaderboardHtml,
      feedHtml,
      renderMobilePanels,
      effectiveTechChoices: techFlow.effectiveTechChoices,
      renderManpowerPanelHtml
    });
  renderHudImpl = renderHud;

  const resize = (): void => resizeClientViewport({ dom: { canvas }, viewportSize });
  window.addEventListener("resize", resize);
  window.visualViewport?.addEventListener("resize", resize);
  resize();
  authFlow.bindAuthUi();

  bindClientUiControls({
    state,
    hud: dom.hud,
    allianceSendBtn,
    mobileAllianceSendBtn,
    allianceBreakBtn,
    mobileAllianceBreakBtn,
    allianceTargetEl,
    mobileAllianceTargetEl,
    allianceBreakIdEl,
    mobileAllianceBreakIdEl,
    techChooseBtn,
    mobileTechChooseBtn,
    techPickEl,
    mobileTechPickEl,
    centerMeBtn,
    centerMeDesktopBtn,
    collectVisibleDesktopBtn,
    collectVisibleMobileBtn,
    captureCancelBtn,
    captureCloseBtn,
    captureTimeEl,
    shardAlertCloseBtn,
    panelCloseBtn,
    panelActionButtons,
    authColorPresetButtons,
    authProfileColorEl,
    authEmailEl,
    authEmailLinkBtn,
    authProfileNameEl,
    authProfileSaveBtn,
    sendAllianceRequest: actionFlow.sendAllianceRequest,
    breakAlliance: actionFlow.breakAlliance,
    chooseTech: actionFlow.chooseTech,
    renderHud,
    centerOnOwnedTile,
    requestViewRefresh,
    collectVisibleYield: actionFlow.collectVisibleYield,
    cancelOngoingCapture: actionFlow.cancelOngoingCapture,
    hideShardAlert: deps.hideShardAlert,
    renderShardAlert,
    renderCaptureProgress,
    setActivePanel,
    syncAuthPanelState
  });

  bindClientNetwork({
    state,
    ws,
    wsUrl,
    firebaseAuth,
    keyFor,
    renderHud,
    setAuthStatus,
    syncAuthOverlay,
    authenticateSocket,
    pushFeed,
    pushFeedEntry,
    clearOptimisticTileState,
    requestViewRefresh,
    applyPendingSettlementsFromServer: actionFlow.applyPendingSettlementsFromServer,
    mergeIncomingTileDetail,
    mergeServerTileWithOptimisticState,
    maybeAnnounceShardSite,
    markDockDiscovered,
    centerOnOwnedTile,
    authProfileNameEl,
    authProfileColorEl,
    defensibilityPctFromTE: techFlow.defensibilityPctFromTE,
    clearPendingCollectVisibleDelta,
    seedProfileSetupFields: seedProfileSetupFieldsFromMain ?? seedProfileSetupFields,
    resetStrategicReplayState,
    setWorldSeed,
    clearRenderCaches,
    buildMiniMapBase,
    shardAlertKeyForPayload,
    showShardAlert,
    combatResolutionAlert,
    wasPredictedCombatAlreadyShown,
    showCaptureAlert,
    requestSettlement: actionFlow.requestSettlement,
    dropQueuedTargetKeyIfAbsent: actionFlow.dropQueuedTargetKeyIfAbsent,
    processActionQueue: actionFlow.processActionQueue,
    clearSettlementProgressForTile: actionFlow.clearSettlementProgressForTile,
    terrainAt,
    requestAttackPreviewForTarget: actionFlow.requestAttackPreviewForTarget,
    openSingleTileActionMenu: actionFlow.openSingleTileActionMenu,
    isTileOwnedByAlly: actionFlow.isTileOwnedByAlly,
    hideShardAlert: deps.hideShardAlert,
    explainActionFailure: actionFlow.explainActionFailure,
    notifyInsufficientGoldForFrontierAction,
    clearSettlementProgressByKey: actionFlow.clearSettlementProgressByKey,
    showCollectVisibleCooldownAlert: deps.showCollectVisibleCooldownAlert,
    formatCooldownShort: actionFlow.formatCooldownShort,
    reconcileActionQueue: actionFlow.reconcileActionQueue,
    revertOptimisticVisibleCollectDelta,
    revertOptimisticTileCollectDelta,
    clearPendingCollectTileDelta,
    playerNameForOwner,
    settlementProgressForTile: actionFlow.settlementProgressForTile,
    COLLECT_VISIBLE_COOLDOWN_MS: deps.COLLECT_VISIBLE_COOLDOWN_MS,
    shouldResetFrontierActionStateForError: actionFlow.shouldResetFrontierActionStateForError
  });

  authFlow.bindFirebaseAuth();

  startClientRuntimeLoop(state, {
    canvas,
    ctx,
    initTerrainTextures,
    isMobile,
    keyFor,
    wrapX,
    wrapY,
    parseKey,
    selectedTile,
    settlementProgressForTile: actionFlow.settlementProgressForTile,
    tileVisibilityStateAt,
    crystalTargetingTone: actionFlow.crystalTargetingTone,
    startingExpansionArrowTargets: originSelection.startingExpansionArrowTargets,
    drawTerrainTile,
    drawForestOverlay,
    effectiveOverlayColor,
    overlayVariantIndexAt,
    dockOverlayVariants,
    drawCenteredOverlay,
    builtResourceOverlayForTile,
    resourceOverlayForTile,
    economicStructureOverlayAlpha,
    drawCenteredOverlayWithAlpha,
    resourceOverlayScaleForTile,
    drawResourceCornerMarker,
    drawRoadOverlay,
    resourceColor,
    shardOverlayForTile,
    drawShardFallback,
    drawTownOverlay,
    hasCollectableYield,
    structureAccentColor,
    structureOverlayImages,
    constructionRemainingMsForTile: actionFlow.constructionRemainingMsForTile,
    formatCountdownClock: actionFlow.formatCountdownClock,
    drawStartingExpansionArrow,
    drawBarbarianSkullOverlay: deps.drawBarbarianSkullOverlay,
    shouldDrawOwnershipBorder,
    borderColorForOwner,
    isTileOwnedByAlly: actionFlow.isTileOwnedByAlly,
    borderLineWidthForOwner,
    drawExposedTileBorder,
    isTownSupportNeighbor: originSelection.isTownSupportNeighbor,
    isTownSupportHighlightableTile: originSelection.isTownSupportHighlightableTile,
    drawIncomingAttackOverlay: deps.drawIncomingAttackOverlay,
    settlePixelWanderPoint: settlePixelWanderPointFromModule,
    worldToScreen,
    isDockRouteVisibleForPlayer,
    computeDockSeaRoute,
    toroidDelta,
    drawAetherBridgeLane,
    drawMiniMap,
    maybeRefreshForCamera,
    renderHud,
    renderCaptureProgress,
    renderShardAlert,
    cleanupExpiredSettlementProgress: actionFlow.cleanupExpiredSettlementProgress,
    processDevelopmentQueue: actionFlow.processDevelopmentQueue,
    clearOptimisticTileState,
    dropQueuedTargetKeyIfAbsent: actionFlow.dropQueuedTargetKeyIfAbsent,
    pushFeed,
    processActionQueue: actionFlow.processActionQueue,
    shouldPreserveOptimisticExpandByKey,
    requestViewRefresh,
    reconcileActionQueue: actionFlow.reconcileActionQueue
  });

  bindClientMapInput(state, {
    canvas,
    miniMapEl,
    holdBuildMenuEl,
    tileActionMenuEl,
    wrapX,
    wrapY,
    keyFor,
    worldTileRawFromPointer,
    computeDragPreview,
    requestViewRefresh,
    maybeRefreshForCamera,
    handleTileSelection: actionFlow.handleTileSelection,
    cancelOngoingCapture: actionFlow.cancelOngoingCapture,
    hideHoldBuildMenu: actionFlow.hideHoldBuildMenu,
    hideTileActionMenu: actionFlow.hideTileActionMenu,
    clearCrystalTargeting: actionFlow.clearCrystalTargeting,
    renderMobilePanels,
    queueSpecificTargets: actionFlow.queueSpecificTargets,
    processActionQueue: actionFlow.processActionQueue,
    pushFeed,
    openBulkTileActionMenu: actionFlow.openBulkTileActionMenu,
    isTileOwnedByAlly: actionFlow.isTileOwnedByAlly,
    requestAttackPreviewForHover: actionFlow.requestAttackPreviewForHover,
    interactionFlags: actionFlow.mapInteractionFlags
  });
};
