const DURABLE_COMMAND_TYPES = [
  "ATTACK",
  "EXPAND",
  "BREAKTHROUGH_ATTACK",
  "SETTLE",
  "BUILD_FORT",
  "BUILD_OBSERVATORY",
  "BUILD_SIEGE_OUTPOST",
  "BUILD_ECONOMIC_STRUCTURE",
  "CANCEL_FORT_BUILD",
  "CANCEL_STRUCTURE_BUILD",
  "REMOVE_STRUCTURE",
  "CANCEL_SIEGE_OUTPOST_BUILD",
  "CANCEL_CAPTURE",
  "UNCAPTURE_TILE",
  "COLLECT_TILE",
  "COLLECT_VISIBLE",
  "CHOOSE_TECH",
  "CHOOSE_DOMAIN",
  "OVERLOAD_SYNTHESIZER",
  "SET_CONVERTER_STRUCTURE_ENABLED",
  "REVEAL_EMPIRE",
  "REVEAL_EMPIRE_STATS",
  "CAST_AETHER_BRIDGE",
  "CAST_AETHER_WALL",
  "SIPHON_TILE",
  "PURGE_SIPHON",
  "CREATE_MOUNTAIN",
  "REMOVE_MOUNTAIN",
  "AIRPORT_BOMBARD",
  "COLLECT_SHARD"
] as const;

export const RESTART_PARITY_COMMAND_TYPES = DURABLE_COMMAND_TYPES;
export const ACCEPTANCE_RESOLUTION_COMMAND_TYPES = DURABLE_COMMAND_TYPES;
export const RECONNECT_COMMAND_TYPES = DURABLE_COMMAND_TYPES;
