const DURABLE_COMMAND_TYPES = [
  "ATTACK",
  "EXPAND",
  "BREAKTHROUGH_ATTACK",
  "SETTLE",
  "BUILD_FORT",
  "BUILD_OBSERVATORY",
  "BUILD_SIEGE_OUTPOST",
  "BUILD_ECONOMIC_STRUCTURE",
  "CANCEL_FORT_BUILD",
  "CANCEL_STRUCTURE_BUILD",
  "REMOVE_STRUCTURE",
  "CANCEL_SIEGE_OUTPOST_BUILD",
  "CANCEL_CAPTURE",
  "UNCAPTURE_TILE",
  "COLLECT_TILE",
  "COLLECT_VISIBLE",
  "CHOOSE_TECH",
  "CHOOSE_DOMAIN",
  "OVERLOAD_SYNTHESIZER",
  "SET_CONVERTER_STRUCTURE_ENABLED",
  "REVEAL_EMPIRE",
  "REVEAL_EMPIRE_STATS",
  "CAST_AETHER_BRIDGE",
  "CAST_AETHER_WALL",
  "SIPHON_TILE",
  "PURGE_SIPHON",
  "CREATE_MOUNTAIN",
  "REMOVE_MOUNTAIN",
  "AIRPORT_BOMBARD",
  "COLLECT_SHARD"
] as const;

const PHASE4_NON_DURABLE_COMMAND_TYPES = [
  "ATTACK_PREVIEW",
  "SET_TILE_COLOR",
  "SET_PROFILE",
  "ALLIANCE_REQUEST",
  "ALLIANCE_ACCEPT",
  "ALLIANCE_REJECT",
  "ALLIANCE_CANCEL",
  "ALLIANCE_BREAK",
  "TRUCE_REQUEST",
  "TRUCE_ACCEPT",
  "TRUCE_REJECT",
  "TRUCE_CANCEL",
  "TRUCE_BREAK"
] as const;

export const PHASE4_COMMAND_SURFACE_TYPES = [...DURABLE_COMMAND_TYPES, ...PHASE4_NON_DURABLE_COMMAND_TYPES] as const;
export const RESTART_PARITY_COMMAND_TYPES = DURABLE_COMMAND_TYPES;
export const ACCEPTANCE_RESOLUTION_COMMAND_TYPES = DURABLE_COMMAND_TYPES;
export const RECONNECT_COMMAND_TYPES = DURABLE_COMMAND_TYPES;
